-- Your SQL goes here
CREATE TABLE emailers (
  id SERIAL PRIMARY KEY,
  search_param VARCHAR NOT NULL,
  authentication_id VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  frequency VARCHAR NOT NULL,
  max_price FLOAT,
  min_price FLOAT,
  no_bedrooms INTEGER,
  insurance FLOAT NOT NULL,
  vacancy FLOAT NOT NULL,
  property_management FLOAT NOT NULL,
  capex FLOAT NOT NULL,
  repairs FLOAT NOT NULL,
  utilities FLOAT NOT NULL,
  down_payment FLOAT NOT NULL,
  closing_cost FLOAT NOT NULL,
  loan_interest FLOAT NOT NULL,
  loan_months FLOAT NOT NULL,
  additional_monthly_expenses FLOAT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP,
  active BOOLEAN NOT NULL
);